config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :api, defaults: { format: :json } do
    post 'login', to: 'authentication#authenticate'
    post 'signup', to: 'users#create' 
    resources :allposts
    resources :users do
      resources :posts do
        resources :comments
      end
    end
  end
  root "users#index"
  get "/users/", to: "users#index", as: 'users'
  get "/users/:user_id", to: "users#show"
  get "/users/:user_id/posts", to: "posts#index", as: 'user_post'
  get '/users/:user_id/posts/new', to: 'posts#new', as: 'new_post' # new
  get "/users/:user_id/posts/:post_id", to: "posts#show", as: 'post_comments'
  get "/users/:user_id/posts/:post_id/comments/new", to: "comments#new", as: "new_comment"


  post '/users/:user_id/posts/new', to: 'posts#create' # create
  post '/users/:user_id/posts/:post_id/comments/new', to: 'comments#create' # create
  post "/users/:user_id/posts/:post_id/like", to: "likes#like", as: "user_create_post_like"
  delete "/users/:user_id/posts/:post_id", to: "posts#destroy", as: "destroy_post"
  delete "/users/:user_id/posts/:post_id/comments/:id", to: "comments#destroy", as: "destroy_comments"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: { message: ' field cannot be blank' }
  validates :title, length: { maximum: 250, too_long: '250 characters is the maximum allowed for the title' }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }

  def update_author_posts
    counter = author.posts.count('id')
    author.update(posts_counter: counter)
  end

  def recent_comments(quantity)
    comments.order(created_at: :desc).limit(quantity)
  end

  def five_recent_comments
    recent_comments(5)
  end

  def comments_counter
    comments.count
  end

  def likes_counter
    likes.count
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  before_action :set_posts

  def show; end

  def index
    # @posts.each do |post|
    #   render json: {
    #     id: post.id,
    #     title: post.title,
    #     text: post.text,
    #     comments_counter: post.comments_counter,
    #     likes_counter: post.likes_counter,
    #     author_id: post.author_id
    #   }
    # end
    render json: @posts
  end

  private

  def set_posts
    @user = User.find(params[:user_id])
    @posts = @user.recent_posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.recent_posts
    @limit = params[:limit] unless params[:limit].nil?
  end

  def show
    @current_user = current_user
    @user = current_user
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
  end

  def new
    @user = User.find(params[:user_id])
    @current_user = current_user
    @post = Post.new
    respond_to do |format|
      format.html { render :new }
    end
  end

  def create
    if user_signed_in?
      @user = current_user
      # new object from params
      @post = @user.posts.create(params.require(:post).permit(:title, :text))
      if @post.save
        flash[:notice] = 'Post saved successfully'
        redirect_to user_post_url
      else
        flash.now[:error] = 'Error: Post could not be saved'
        render :new, locals: { post: @post }
      end
    else
      flash.now[:error] = 'Error: Please sign up to make a posts.'
      redirect_to root_path
    end
  end

  def destroy
    @user = current_user
    @post = @user.posts.find(params[:post_id])
    @delete_post = @user.posts.destroy(@post.id)
    if @post.destroy
      flash[:notice] = 'Post deleted successfully'
      redirect_to user_post_url
    else
      flash.now[:error] = 'Error: Post could not be deleted'
      render :new, locals: { post: @post }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: post, url: new_post_path, method: :post, local: true, scope: :post do |f| %>
  <div>
  <%= f.label :title %>

  <%= f.text_field :title,
  size: "50x12",
placeholder: "Write your title here..."
  %>
</div>

<div>
  <%= f.label :Text %>

  <%= f.text_area :text,
size: "50x12",
placeholder: "Write your post here..."
  %>
</div>
<%= f.submit "Submit" %>
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
      <% @post.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<% end %>

app/views/posts/_post_card.html.erb
 <a href="/users/<%= @user.id %>/posts/<%= post.id %>">
<div class="post">
   <p class="post-title"><%= post.title %></p>
   <p class="post-text"><%= post.text %></p>
</div>
<div class="comment-cont">
   <% post.five_recent_comments.each do |comment| %>
   <p><%= comment.text %></p>
<% end %>
   <div class="interact"><span class="post-comment">Comments: <%= post.comments_counter %></span><span class="post-like">Likes: <%= post.likes_counter %></span></div>
</div>
</a>

app/views/posts/_user_card.html.erb
<div class="user">
  <a class="user" href="/users/<%= user.id %>">
    <div class="user">
    <div class="profile-pic">
        <%= image_tag('profile-pic.jpg', :size => "100x100") %>
    </div>
    <div class="text-holder">
        <p><%= user.name %></p>
        <p>Number of Posts: <%= user.posts_counter %></p>
    </div>
    </div>
  </a>
</div>

app/views/posts/index.html.erb
<div class="posts-info">
<%= render 'user_card', user: @user %>
    <button> <%= link_to 'Add Post', new_post_path %></button>
<% @posts.includes(:comments).each do |post| %>
<%= render 'post_card', post: post %>
<% end %>

</div>

app/views/posts/new.html.erb
<%= render 'user_card', user: @user %>
<h1>New Post</h1>
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<div class="post">
   <p class="post-title"><%= @post.title %> By <%= @user.name %></p>
      <div class="interact"><span class="post-comment">Comments: <%= @post.comments_counter %></span><span class="post-like">Likes: <%= @post.likes_counter %></span></div>
   <p class="post-text"><%= @post.text %></p>
</div>
    <button> <%= link_to 'Add Comment', new_comment_path %></button>
     <%= button_to 'Like', user_create_post_like_url %>
        <% if can? :delete, @post %>
          <%= button_to 'Delete', destroy_post_path, method: :delete %>
          <% end %>
<div class="comment-cont">
   <% @post.recent_comments(100).each do |comment| %>
   <p> <%= comment.author.name %>: <%= comment.text %></p>
   <% if can? :delete, comment %>
      <%= button_to 'Delete', destroy_comments_path(comment.post.author, comment.post, comment), method: :delete %>
<% end %>
<% end %>
</div>